version: "2"

services:
  apis:
    image: thanhson1085/api-seed
    depends_on:
      - db
      - redis
    networks:
      - front-net
      - back-net

  site:
    image: thanhson1085/site-seed
    networks:
      - front-net

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - back-net

  db:
    image: mongo:3.2
    container_name: db
    volumes:
        - "mongodb:/data/db"
    networks:
      - back-net

  kibana:
    image: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - monitor-net

  elasticsearch:
    image: elasticsearch
    networks:
      - monitor-net

  fluentd:
    build: ./monitor/fluentd/.
    image: thanhson1085/fluentd-es
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
    environment:
      - ES_PORT_9200_TCP_ADDR=elasticsearch
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitor-net

  kapacitor:
    image: kapacitor
    ports:
      - "9092:9092"
    depends_on:
      - influxdb
    volumes:
      - ./monitor/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
    networks:
      - monitor-net

  influxdb:
    image: influxdb 
    networks:
      - monitor-net
    ports:
      - "8083:8083"
      - "8086:8086"

  telegraf:
    image: telegraf
    depends_on:
      - influxdb
    environment:
      - "HOST_PROC=/rootfs/proc"
      - "HOST_SYS=/rootfs/sys"
      - "HOST_ETC=/rootfs/etc"
    volumes:
      - ./monitor/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    networks:
      - monitor-net

  gateway:
    image: nginx
    container_name: gateway
    volumes:
      - ./app.template:/etc/nginx/conf.d/default.conf
      - ./nginx.template:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - apis
    networks:
      - front-net

volumes:
    mongodb:
    apis:
networks:
  front-net:
  back-net:
  monitor-net:
